---
abstract: 'Interpolation made easy'
author:
  - 'Binary.com <perl@binary.com>'
build_requires:
  Carp: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Math::Cephes::Matrix: '0'
  Module::Pluggable: '0'
  Module::Runtime: '0'
  Moo: '0'
  Moo::Role: '0'
  MooX::Traits: '0'
  Number::Closest::XS: '0'
  POSIX: '0'
  Scalar::Util: '0'
  Test::More: '0'
  Try::Tiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141520'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-Function-Interpolator
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
version: '0.06'
